### ISSUE TITLE
NextQuestion버튼 Bug

### ISSUE THREAD

**Issue by kimhyooo** [kimhyooo/open_quiz_mid#4]
아무것도 안 풀고 NextQuestion버튼을 누르면 안 풀었는데도 불구하고,푼 문항 수가 증가하는 Bug가 있음.

**Comment by khjin2443** [comment]
3a9f887b92b80fba2d0f8f4f20409ebe04c29ea9

버그 수정 -> if, else로 나누어 각각 메시지 세팅, 아무런 선택이 없을경우에는 count -- 해주어 카운트 수 유지, 그 외 카운트 증가

**Comment by kimhyooo** [comment]
혜진Collaborator 아주아주 잘 했습니다bbb
