### ISSUE TITLE
타이머 오류

### ISSUE THREAD

**Issue by khjin2443** [kimhyooo/open_quiz_mid#9]
퀴즈 진행시 퀴즈 풀이가 완료가 되어도 타이머 시간이 계속해서 흐르고 있어서 타이머 시간이 끝나면 점수 0점으로 최종화면이 노출됨

**Comment by kimhyooo** [comment]
타이머 버그는 해결 
ex) 10문제 다 맞추고 10초 남았으면 10초 후에 결과창이 뜨는 버그

### 랭크 버그는 해결x

**Comment by kimhyooo** [comment]
@tgb06063 가 랭크 버그 해결

**Comment by tgb06063** [comment]
해결 완료
